# Linter Options
options:
  # Treat warnings as errors
  max-warnings: 0

# File Options
files:
  include: 'src/sass/**/*.scss'

# Rule Configuration
rules:
  force-element-nesting:
    - 0
  hex-length:
    - 2
    - style: long
  indentation:
    - 2
    - size: 4
  nesting-depth:
    - 2
    - max-depth: 6
  no-color-literals:
    - 0  # TODO: Remove this when resolving #9
  no-ids:
    - 0
  no-important:
    - 0
  no-qualifying-elements:
    - 0
  property-sort-order:
    - 2
    - order: concentric

# Auto-Fix Configuration
resolvers:
  # Prevent removing comments
  no-css-comments: 0
  # Prevent removing "!important"
  no-important: 0
