# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Raise an error if more than 50 warnings are generated
  max-warnings: 0

# File Options
files:
  include: 'src/sass/**/*.s+(a|c)ss'

# Rule Configuration
rules:
  # Style Guide
  indentation:
    - 2
    - size: 4
  property-sort-order:
    - 2
    - order: concentric
